"""empty message

Revision ID: 42acf788914b
Revises: 
Create Date: 2021-07-02 00:25:51.430409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42acf788914b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.String(length=128), nullable=False))
    op.add_column('product', sa.Column('price', sa.FLOAT(precision=8), nullable=True))
    op.add_column('product', sa.Column('inventory', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('owner', sa.String(length=63), nullable=True))
    op.add_column('product', sa.Column('category', sa.String(length=63), nullable=True))
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    op.drop_column('product', 'category')
    op.drop_column('product', 'owner')
    op.drop_column('product', 'inventory')
    op.drop_column('product', 'price')
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
